-- Setup Tabel untuk Modul Gate & Scanner
-- Silakan copy semua kode ini dan jalankan di SQL Editor Supabase

-- 1. Buat Tabel Gate Logs
CREATE TABLE gate_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number text NOT NULL,
  truck_plate text NOT NULL,
  driver_name text,
  commodity text,
  bruto_weight numeric,
  tarra_weight numeric,
  netto_weight numeric,
  gate_in_time timestamp with time zone,
  gate_out_time timestamp with time zone,
  status text DEFAULT 'DI DALAM PELABUHAN',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Masukkan Data Contoh (Dummy Data) yang sedang ada di dalam pelabuhan
INSERT INTO gate_logs (document_number, truck_plate, driver_name, commodity, gate_in_time, status) VALUES 
('SJ-2026-00123', 'B 9012 KJL', 'Supriadi', 'Pasir Besi (Curah Kering)', timezone('utc'::text, now()), 'DI DALAM PELABUHAN');

-- 3. Buka Akses (RLS)
ALTER TABLE gate_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for gate_logs" ON gate_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for gate_logs" ON gate_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for gate_logs" ON gate_logs FOR DELETE USING (true);
CREATE POLICY "Allow public update access for gate_logs" ON gate_logs FOR UPDATE USING (true);
