-- Setup Tabel Operasional JPT (Manifests)
-- Silakan copy semua kode ini dan jalankan di SQL Editor Supabase seperti sebelumnya

CREATE TABLE manifests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manifest_number text NOT NULL,
  consignee text NOT NULL,
  komoditas text NOT NULL,
  status_do text DEFAULT 'Menunggu Penebusan',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Masukkan 1 Data Contoh agar tidak kosong
INSERT INTO manifests (manifest_number, consignee, komoditas, status_do) VALUES 
('BL-2026/06/0002', 'PT SAKA AGUNG', 'SEMEN TIGA RODA', 'DO DIRILIS');

-- Buka akses agar bisa dibaca dan ditulis oleh aplikasi
ALTER TABLE manifests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for manifests" ON manifests FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for manifests" ON manifests FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for manifests" ON manifests FOR DELETE USING (true);
CREATE POLICY "Allow public update access for manifests" ON manifests FOR UPDATE USING (true);
