-- Setup Tabel untuk Operasional PBM (Bongkar Muat)
-- Silakan copy semua kode ini dan jalankan di SQL Editor Supabase

-- 1. Buat Tabel Rencana Bongkar Muat (PBM Plans)
CREATE TABLE pbm_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ship_name text NOT NULL,
  total_tonnage numeric NOT NULL,
  crane_allocation text NOT NULL,
  foreman_name text NOT NULL,
  status text DEFAULT 'Terjadwal',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Buat Tabel Catatan Tally Lapangan (PBM Tally Logs)
CREATE TABLE pbm_tally_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  truck_plate text NOT NULL,
  foreman_name text NOT NULL,
  tonnage numeric NOT NULL,
  status text DEFAULT 'Dimuat',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Masukkan Data Contoh (Dummy Data)
INSERT INTO pbm_plans (ship_name, total_tonnage, crane_allocation, foreman_name) VALUES 
('MV. Meratus 01', 15000, 'Crane Darat 1 (Kapasitas 40T)', 'Jaka Supriadi');

INSERT INTO pbm_tally_logs (truck_plate, foreman_name, tonnage) VALUES 
('B 9012 KJL', 'Jaka Supriadi', 30),
('B 9013 KJL', 'Jaka Supriadi', 32);

-- 4. Buka Akses (RLS)
ALTER TABLE pbm_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE pbm_tally_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for pbm_plans" ON pbm_plans FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for pbm_plans" ON pbm_plans FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for pbm_plans" ON pbm_plans FOR DELETE USING (true);
CREATE POLICY "Allow public update access for pbm_plans" ON pbm_plans FOR UPDATE USING (true);

CREATE POLICY "Allow public read access for pbm_tally_logs" ON pbm_tally_logs FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for pbm_tally_logs" ON pbm_tally_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for pbm_tally_logs" ON pbm_tally_logs FOR DELETE USING (true);
CREATE POLICY "Allow public update access for pbm_tally_logs" ON pbm_tally_logs FOR UPDATE USING (true);
