-- Setup Tabel untuk Modul Biro Keuangan (Billing / Invoicing)
-- Silakan copy semua kode ini dan jalankan di SQL Editor Supabase

-- 1. Buat Tabel Invoices
CREATE TABLE invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number text NOT NULL UNIQUE,
  client_name text NOT NULL,
  service_type text NOT NULL, -- PBM / JPT
  reference_id text NOT NULL, -- ID dari Kapal / Manifest
  total_tonnage numeric NOT NULL,
  base_tariff numeric NOT NULL,
  subtotal numeric NOT NULL,
  tax_amount numeric NOT NULL,
  grand_total numeric NOT NULL,
  status text DEFAULT 'Unpaid', -- Unpaid / Paid
  due_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Masukkan Data Contoh (Dummy Data)
INSERT INTO invoices (invoice_number, client_name, service_type, reference_id, total_tonnage, base_tariff, subtotal, tax_amount, grand_total, status, due_date) VALUES 
('INV-PBM-26001', 'PT. Semen Kupang', 'PBM', 'MV. Contoh 01', 15000, 50000, 750000000, 82500000, 832500000, 'Paid', timezone('utc'::text, now() + interval '14 days'));

-- 3. Buka Akses (RLS)
ALTER TABLE invoices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for invoices" ON invoices FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for invoices" ON invoices FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for invoices" ON invoices FOR DELETE USING (true);
CREATE POLICY "Allow public update access for invoices" ON invoices FOR UPDATE USING (true);
