-- Setup Tabel Tambahan untuk Master Data (Hak Akses & Tarif Pajak)
-- Silakan copy semua kode ini dan jalankan di SQL Editor Supabase

-- 1. Buat Tabel Hak Akses Pengguna (Staff Users)
CREATE TABLE staff_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  username text NOT NULL,
  role text NOT NULL,
  status text DEFAULT 'Aktif',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Buat Tabel Tarif & Pajak (Tariffs)
CREATE TABLE tariffs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  status text DEFAULT 'Aktif',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Masukkan Data Contoh
INSERT INTO staff_users (name, username, role, status) VALUES 
('Budi Santoso', 'budi.admin', 'Admin', 'Aktif'),
('Jaka Supriadi', 'jaka.tally', 'Tally Lapangan', 'Aktif');

INSERT INTO tariffs (code, name, description, status) VALUES 
('TRF-001', 'PPN', 'Pajak Pertambahan Nilai 11%', 'Aktif'),
('TRF-002', 'JPT-Dasar', 'Tarif Dasar Jasa Pengurusan Transportasi', 'Aktif');

-- 4. Buka Akses (RLS)
ALTER TABLE staff_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE tariffs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for staff_users" ON staff_users FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for staff_users" ON staff_users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for staff_users" ON staff_users FOR DELETE USING (true);
CREATE POLICY "Allow public update access for staff_users" ON staff_users FOR UPDATE USING (true);

CREATE POLICY "Allow public read access for tariffs" ON tariffs FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for tariffs" ON tariffs FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for tariffs" ON tariffs FOR DELETE USING (true);
CREATE POLICY "Allow public update access for tariffs" ON tariffs FOR UPDATE USING (true);
