-- Setup Tabel Master Data untuk SILOP
-- Silakan copy semua kode ini dan jalankan di SQL Editor Supabase

-- 1. Buat Tabel Kapal (Ships)
CREATE TABLE ships (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name text NOT NULL,
  type text,
  status text DEFAULT 'Aktif',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Buat Tabel Klien (Clients)
CREATE TABLE clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name text NOT NULL,
  type text,
  status text DEFAULT 'Aktif',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Masukkan Data Contoh (Dummy Data)
INSERT INTO ships (code, name, type, status) VALUES 
('SHP-001', 'MV. Meratus 01', 'General Cargo', 'Aktif'),
('SHP-002', 'KM. Logistik Nusantara', 'Curah Kering', 'Aktif');

INSERT INTO clients (code, name, type, status) VALUES 
('CLI-001', 'PT Semen Bangsa', 'BUMN', 'Aktif'),
('CLI-002', 'PT Indo Trucking', 'Swasta', 'Aktif');

-- 4. Buka akses agar bisa dibaca dan ditulis oleh aplikasi (Anon)
-- PERINGATAN: Di tahap produksi, akses ini harus dibatasi dengan Row Level Security (RLS)
ALTER TABLE ships ENABLE ROW LEVEL SECURITY;
ALTER TABLE clients ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access for ships" ON ships FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for ships" ON ships FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for ships" ON ships FOR DELETE USING (true);

CREATE POLICY "Allow public read access for clients" ON clients FOR SELECT USING (true);
CREATE POLICY "Allow public insert access for clients" ON clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete access for clients" ON clients FOR DELETE USING (true);
